version: 2

machine:
  xcode:
    version: 8.2

jobs:
  test:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: yarn --no-progress
      - run: yarn test

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
